server:
  port: 8080
spring:
  application:
    name: springcloud-order-consumer8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://wangxin:wangxin@localhost:7001/eureka/,http://wangxin:wangxin@localhost:7002/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoint:
    health:
      show-details: always
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
