server:
  port: 8088

spring:
  profiles:
    active: dev
management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
