server:
  port: 8084
spring:
  application:
    name: spring-cloud-order-fengin-hystrix8083
#  security:
#    user:
#      name: wangxin
#      password: wangxin
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://wangxin:wangxin@localhost:7001/eureka/,http://wangxin:wangxin@localhost:7002/eureka/
    fetch-registry: true
    register-with-eureka: true
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    #配置服务降级全局超时时间
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
        timeout:
          enabled: true #开启hystrix,为false将超时控制交给ribbon
ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试，如果eureka中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000  #请求连接的超时时间
  ReadTimeout: 3000 #请求处理的超时时间
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

